Revert "[modules] Separately track whether an identifier's preprocessor information and"
This adds a testcase and reverts commit
dec469b8c5c697fcf99f637c15e591f522475d2a. It fixes the error below:

$ rm -rf tmp; clang -fmodules standalone.c -fmodules-cache-path=tmp -fsyntax-only -I Inputs
standalone.c:3:6: error: variable has incomplete type 'void'
void foo __P(());
     ^
standalone.c:3:9: error: expected ';' after top level declarator
void foo __P(());
        ^
        ;
2 errors generated.

For detailed info see rdar://problem/28410377

---
Some changes were necessary to maintain Vassil's module related fix in
r264913.

Conflicts:
    lib/Serialization/ASTWriter.cpp